
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-user?characterEncoding=utf8
    username: root
    password: 133309
#mybatis配置
#mybatis:
##实体类所在包名
#  type-aliases-package: com.wx.securitydemo1.domain
mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.wx.securitydemo1.domain.*
#  config-location: classpath:mybatis-config.xml

mapper:
  mappers: com.wx.securitydemo1.utils.IBaseDao
  identity: MYSQL